import AppKit
import Combine
import CoreGraphics
import Foundation

@MainActor
final class ClipboardSyncController: ObservableObject {
    struct PasteboardContent {
        let text: String?
        let typeNames: Set<String>
    }

    static let enabledKey = "plink.clipboardSyncEnabled"
    static let maximumTextBytes = 32_768

    @Published private(set) var enabled: Bool
    var onTextChanged: (@MainActor @Sendable (String) async throws -> Void)?

    private static let refusedTypeNames: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private let defaults: UserDefaults
    private let pollInterval: Duration
    private let isUnlocked: @MainActor () -> Bool
    private let changeCount: @MainActor () -> Int
    private let readContent: @MainActor () -> PasteboardContent
    private let writeText: @MainActor (String) -> (success: Bool, changeCount: Int)
    private var connected = false
    private var pollTask: Task<Void, Never>?
    private var sendTask: Task<Void, Never>?
    private var baselineChangeCount: Int?

    init(
        defaults: UserDefaults = .standard,
        pollInterval: Duration = .milliseconds(500),
        isUnlocked: @escaping @MainActor () -> Bool = ClipboardSyncController.systemIsUnlocked,
        changeCount: @escaping @MainActor () -> Int = { NSPasteboard.general.changeCount },
        readContent: @escaping @MainActor () -> PasteboardContent = ClipboardSyncController.readGeneralPasteboard,
        writeText: @escaping @MainActor (String) -> (success: Bool, changeCount: Int) = ClipboardSyncController.writeGeneralPasteboard
    ) {
        self.defaults = defaults
        self.pollInterval = pollInterval
        self.isUnlocked = isUnlocked
        self.changeCount = changeCount
        self.readContent = readContent
        self.writeText = writeText
        enabled = defaults.bool(forKey: Self.enabledKey)
    }

    deinit {
        pollTask?.cancel()
        sendTask?.cancel()
    }

    func start() {
        guard pollTask == nil else { return }
        pollOnce()
        pollTask = Task { @MainActor [weak self] in
            while !Task.isCancelled {
                guard let interval = self?.pollInterval else { return }
                do { try await Task.sleep(for: interval) } catch { return }
                self?.pollOnce()
            }
        }
    }

    func stop() {
        pollTask?.cancel()
        pollTask = nil
        cancelSend()
        resetBaseline()
    }

    func setEnabled(_ enabled: Bool) {
        guard self.enabled != enabled else { return }
        self.enabled = enabled
        defaults.set(enabled, forKey: Self.enabledKey)
        if !enabled { cancelSend() }
        resetBaseline()
    }

    func setConnected(_ connected: Bool) {
        guard self.connected != connected else { return }
        self.connected = connected
        if !connected { cancelSend() }
        resetBaseline()
    }

    @discardableResult
    func receive(_ text: String) -> Bool {
        cancelSend()
        guard enabled, connected, isUnlocked(), text.utf8.count <= Self.maximumTextBytes else { return false }
        let result = writeText(text)
        guard result.success, changeCount() == result.changeCount else { return false }
        baselineChangeCount = result.changeCount
        return true
    }

    func pollOnce() {
        guard enabled, connected, isUnlocked() else {
            cancelSend()
            resetBaseline()
            return
        }
        let currentChangeCount = changeCount()
        guard let baselineChangeCount else {
            self.baselineChangeCount = currentChangeCount
            return
        }
        guard currentChangeCount != baselineChangeCount else { return }
        self.baselineChangeCount = currentChangeCount
        cancelSend()

        let content = readContent()
        guard changeCount() == currentChangeCount else { return }
        guard content.typeNames.isDisjoint(with: Self.refusedTypeNames),
              let text = content.text,
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
              text.utf8.count <= Self.maximumTextBytes else { return }
        send(text, changeCount: currentChangeCount)
    }

    private func resetBaseline() {
        baselineChangeCount = nil
    }

    private func cancelSend() {
        sendTask?.cancel()
        sendTask = nil
    }

    private func send(_ text: String, changeCount expectedChangeCount: Int) {
        cancelSend()
        guard let onTextChanged else { return }
        sendTask = Task { @MainActor [weak self] in
            await withTaskGroup(of: Void.self) { group in
                group.addTask { [weak self] in
                    await self?.deliver(
                        text,
                        changeCount: expectedChangeCount,
                        using: onTextChanged
                    )
                }
                group.addTask {
                    do { try await Task.sleep(for: .seconds(3)) } catch {}
                }
                _ = await group.next()
                group.cancelAll()
            }
        }
    }

    private func deliver(
        _ text: String,
        changeCount expectedChangeCount: Int,
        using onTextChanged: @MainActor @Sendable (String) async throws -> Void
    ) async {
        guard !Task.isCancelled,
              enabled,
              connected,
              isUnlocked(),
              changeCount() == expectedChangeCount else { return }
        do { try await onTextChanged(text) } catch {}
    }

    static func systemIsUnlocked() -> Bool {
        guard let session = CGSessionCopyCurrentDictionary() as? [String: Any] else { return false }
        return (session["CGSSessionScreenIsLocked"] as? Bool) != true
    }

    static func readGeneralPasteboard() -> PasteboardContent {
        let pasteboard = NSPasteboard.general
        let typeNames = Set((pasteboard.types ?? []).map(\.rawValue))
        guard typeNames.isDisjoint(with: refusedTypeNames) else {
            return PasteboardContent(text: nil, typeNames: typeNames)
        }
        return PasteboardContent(text: pasteboard.string(forType: .string), typeNames: typeNames)
    }

    static func writeGeneralPasteboard(_ text: String) -> (success: Bool, changeCount: Int) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        let success = pasteboard.setString(text, forType: .string)
        return (success, pasteboard.changeCount)
    }
}
