import Foundation
import PlinkCore
import Testing
@testable import PlinkMac

struct CallPanelTests {
    @Test func elapsedStartsAtObservedActiveAndResetsForReplacement() {
        let start = ContinuousClock.now
        var state = CallPanelPresentation()
        var call = MacCallSession()
        call.connected(phoneID: "fixture")
        call.ringing(number: nil)
        state.update(call: call, serviceConnected: true, allowed: true, now: start)
        #expect(state.elapsed(at: start.advanced(by: .seconds(10))) == nil)
        call.setActive(true)
        state.update(call: call, serviceConnected: true, allowed: true, now: start.advanced(by: .seconds(10)))
        #expect(state.elapsed(at: start.advanced(by: .seconds(11))) == "00:01")
        state.update(call: call, serviceConnected: true, allowed: false, now: start.advanced(by: .seconds(12)))
        state.update(call: call, serviceConnected: true, allowed: true, now: start.advanced(by: .seconds(15)))
        #expect(state.elapsed(at: start.advanced(by: .seconds(15))) == "00:05")
        call.setActive(false)
        call.ringing(number: nil)
        state.update(call: call, serviceConnected: true, allowed: true, now: start.advanced(by: .seconds(16)))
        #expect(state.elapsed(at: start.advanced(by: .seconds(17))) == nil)
    }

    @Test func opensOnlyForObservedCallsAndClosingDoesNotEndCall() throws {
        var state = CallPanelPresentation()
        var call = MacCallSession()
        call.connected(phoneID: "fixture")
        state.update(call: call, serviceConnected: true, allowed: true)
        #expect(!state.visible)
        call.ringing(number: nil)
        state.update(call: call, serviceConnected: true, allowed: true)
        #expect(state.visible)
        #expect(state.caller == "Unknown caller")
        let context = try #require(call.context)
        state.close()
        #expect(call.phase == .ringing)
        state.update(call: call, serviceConnected: true, allowed: true)
        #expect(!state.visible)
        call.setActive(true)
        state.update(call: call, serviceConnected: true, allowed: true)
        #expect(!state.visible)
        #expect(call.context == context)
        call.setActive(false)
        state.update(call: call, serviceConnected: true, allowed: true)
        call.ringing(number: "Fixture caller")
        state.update(call: call, serviceConnected: true, allowed: true)
        #expect(state.visible)
        #expect(state.context != context)
    }

    @Test func lockDisconnectUncertaintyAndReplacementInvalidateActions() throws {
        var state = CallPanelPresentation()
        var call = MacCallSession()
        call.connected(phoneID: "fixture")
        call.ringing(number: nil)
        state.update(call: call, serviceConnected: true, allowed: false)
        #expect(!state.visible)
        state.update(call: call, serviceConnected: true, allowed: true)
        let context = try #require(state.context)
        #expect(state.permits(.answer, context: context, current: call, serviceConnected: true, busy: false, blocked: false))
        #expect(!state.permits(.answer, context: context, current: call, serviceConnected: true, busy: true, blocked: false))
        #expect(!state.permits(.answer, context: context, current: call, serviceConnected: true, busy: false, blocked: true))
        state.update(call: call, serviceConnected: true, allowed: false)
        #expect(!state.permits(.answer, context: context, current: call, serviceConnected: true, busy: false, blocked: false))
        state.update(call: call, serviceConnected: true, allowed: true)
        call.setActive(false)
        call.ringing(number: nil)
        state.update(call: call, serviceConnected: true, allowed: true)
        #expect(!state.permits(.answer, context: context, current: call, serviceConnected: true, busy: false, blocked: false))
        call.markUnconfirmed(context: call.context)
        state.update(call: call, serviceConnected: true, allowed: true)
        #expect(!state.visible)
        call.disconnected()
        state.update(call: call, serviceConnected: false, allowed: true)
        #expect(!state.visible)
        #expect(!state.audioConnected)
    }

    @Test func pendingPhasesDoNotEnableDuplicateActionsAndSCOIsOnlyAStatus() throws {
        var state = CallPanelPresentation()
        var call = MacCallSession()
        call.connected(phoneID: "fixture")
        call.ringing(number: nil)
        state.update(call: call, serviceConnected: true, allowed: true)
        let context = try #require(call.context)
        let began = call.begin(.answer, context: context)
        #expect(began)
        state.update(call: call, serviceConnected: true, allowed: true)
        #expect(state.visible)
        #expect(state.status == "Answering…")
        #expect(!state.permits(.answer, context: context, current: call, serviceConnected: true, busy: false, blocked: false))
        #expect(!state.audioConnected)
        call.setActive(true)
        call.setSCO(true)
        state.update(call: call, serviceConnected: true, allowed: true)
        #expect(state.audioConnected)
        #expect(state.audioLabel == "Bluetooth audio connected")
        call.setSCO(false)
        state.update(call: call, serviceConnected: true, allowed: true)
        #expect(!state.audioConnected)
        #expect(state.audioLabel == "Audio on phone")
        call.ringing(number: "Waiting caller")
        state.update(call: call, serviceConnected: true, allowed: true)
        #expect(!state.visible)
        #expect(!state.audioConnected)
    }
}
